server:
  port: 8080
spring:
  application:
    name: SpringOauth2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
          facebook:
            client-id: ${FB_CLIENT_ID}
            client-secret: ${FB_CLIENT_SECRET}
            scope:
              - email
              - public_profile
              - user_friends
        provider:
          facebook:
            authorization-uri: ${AUTH_URI}
            token-uri: ${TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}


jwt:
  secret: ${JWT_SECRET}

